// Mocks generated by Mockito 5.4.6 from annotations
// in flowfit/test/screens/profile/profile_refresh_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowfit/core/domain/entities/user_profile.dart' as _i5;
import 'package:flowfit/core/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:flowfit/presentation/notifiers/profile_notifier.dart' as _i6;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserProfile?> getLocalProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalProfile, [userId]),
            returnValue: _i4.Future<_i5.UserProfile?>.value(),
          )
          as _i4.Future<_i5.UserProfile?>);

  @override
  _i4.Future<void> saveLocalProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLocalProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalProfile, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserProfile?> getBackendProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBackendProfile, [userId]),
            returnValue: _i4.Future<_i5.UserProfile?>.value(),
          )
          as _i4.Future<_i5.UserProfile?>);

  @override
  _i4.Future<void> saveBackendProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveBackendProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncProfile, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasPendingSync(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingSync, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i3.SyncStatus> watchSyncStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSyncStatus, [userId]),
            returnValue: _i4.Stream<_i3.SyncStatus>.empty(),
          )
          as _i4.Stream<_i3.SyncStatus>);

  @override
  _i4.Future<bool> hasCompletedSurvey(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasCompletedSurvey, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [ProfileNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileNotifier extends _i1.Mock implements _i6.ProfileNotifier {
  MockProfileNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i2.AsyncValue<_i5.UserProfile?>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.AsyncValue<_i5.UserProfile?>>.empty(),
          )
          as _i4.Stream<_i2.AsyncValue<_i5.UserProfile?>>);

  @override
  _i2.AsyncValue<_i5.UserProfile?> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_0<_i5.UserProfile?>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<_i5.UserProfile?>);

  @override
  _i2.AsyncValue<_i5.UserProfile?> get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAsyncValue_0<_i5.UserProfile?>(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.AsyncValue<_i5.UserProfile?>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.AsyncValue<_i5.UserProfile?>? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> loadProfile() =>
      (super.noSuchMethod(
            Invocation.method(#loadProfile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile(_i5.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateField(String? field, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#updateField, [field, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProfile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i5.UserProfile?>? old,
    _i2.AsyncValue<_i5.UserProfile?>? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i2.RemoveListener addListener(
    _i8.Listener<_i2.AsyncValue<_i5.UserProfile?>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
